### ISSUE TITLE
Rendering is pixeled on Mac OS

### ISSUE THREAD

**Issue by harlley** [auchenberg/vscode-browser-preview#32] opened 2019-01-23 12:16 UTC

**Comment by mjurczyk** [comment] 2019-01-23 13:40
#21 ?

**Comment by auchenberg** [comment] 2019-01-23 18:39
Duplicate of #21

**Closed by auchenberg** 2019-01-23 18:39 UTC

**Comment by auchenberg** [comment] 2019-04-09 00:13
Should have been fixed in master. See https://github.com/auchenberg/vscode-browser-preview/issues/75
