### ISSUE TITLE
Add an option to include Cmd-Line Arguments

### ISSUE THREAD

**Issue by c3-william-peng** [auchenberg/vscode-browser-preview#201] opened 2021-06-14 17:42 UTC
It would be nice to have the ability to add our own Cmd Line Arguments to the Chromium executable, as I am trying to add `--app={URL}` to remove the navigation bar and increase space.

**Comment by auchenberg** [comment] 2021-06-14 19:41
Thanks for the issue! Duplicate of https://github.com/auchenberg/vscode-browser-preview/issues/193

**Closed by auchenberg** 2021-06-14 19:41 UTC
Labels: duplicate
