### ISSUE TITLE
Getting weird click event delays

### ISSUE THREAD

**Issue by bzuillsmith** [auchenberg/vscode-browser-preview#42] opened 2019-01-26 04:53 UTC
I tried using this while working on the React Tic Tac Toe tutorial. My click events aren't fully processing right away. I have to click on a box (a <button ...>) and then I have to click somewhere else like on some text on the page before the click event is fully processed and an X or and O appears in the box I clicked first. Click events work fine and immediately in a normal browser though. So it seems like something about the click events and focus aren't always processing correctly.

**Comment by bzuillsmith** [comment] 2019-01-28 03:34
I'm running Windows 10. Have the latest public version of yes code 64-bit. There's nothing special about my screens, they are not high DPI. Everything else about VS Code is working. If I find the time, I'll try to demonstrate this with Hover and click effects in a video.

**Comment by gjsjohnmurray** [comment] 2019-01-29 07:05
I'm seeing something that sounds similar. I'm using the current VSCode Insiders (1.31) on Win64.

It looks to me like a missing repaint, because when I resize the VSCode window the content of my Browser Preview tab refreshes and shows the correct content.

**Comment by bzuillsmith** [comment] 2019-01-29 07:09
That would certainly explain it.

**Comment by auchenberg** [comment] 2019-01-29 19:22
@bzuillsmith @gjsjohnmurray Might be a duplicate of https://github.com/auchenberg/vscode-browser-preview/issues/3?

**Comment by auchenberg** [comment] 2019-01-29 19:47
@bzuillsmith What if you open the browser preview followed by resizing the browser preview? Does thing work more as expect? I suspect this is caused by a wrong initial render.

**Comment by bzuillsmith** [comment] 2019-01-29 19:53
Nope. Resizing doesn't seem to help. I just retried to be sure. I also just tested some hover events and those lag behind in a similar manner -- it's always painting the last hover event and not the most current hover.

**Comment by auchenberg** [comment] 2019-01-29 20:10
Interesting. This sounds like a dup of https://github.com/auchenberg/vscode-browser-preview/issues/26 then :)

**Comment by bzuillsmith** [comment] 2019-02-13 23:11
Yep, definitely seems like a dup. Feel free to close if you'd rather it now show up in the open issues.

**Closed** 2019-02-13 23:13 UTC
Labels: bug
