### ISSUE TITLE
Multiple browser previews open endlessly after installing the extension

### ISSUE THREAD

**Issue by santiagofn** [auchenberg/vscode-browser-preview#163] opened 2020-09-19 06:20 UTC
- **OS**: Ubuntu 20.04
- **VSCode** v1.49.1 (snap package)
- **Browser Preview** v0.6.7

After installing the extension multiple groups of browser previews started opening (and they didn't stop doing it): 
<img src="https://user-images.githubusercontent.com/8375708/93660568-b88a6400-fa26-11ea-9727-5b17c3358786.png" width="800">

I was forced to uninstall the extension and manually closed all the opened groups.

Tried installing the extension again after closing and reopening VSCode but the same thing happened.

**Comment by auchenberg** [comment] 2021-02-20 21:06
Duplicate of https://github.com/auchenberg/vscode-browser-preview/issues/177

**Closed by auchenberg** 2021-02-20 21:06 UTC
