### ISSUE TITLE
Inspect element does not open file

### ISSUE THREAD

**Issue by pitops** [auchenberg/vscode-browser-preview#115] opened 2019-07-06 15:55 UTC
I have tried this in my react app but selecting an element does not do anything. Its a custom boilerplate - is that the issue or is something I have to setup first?

I find this feature pretty neat!

**Comment by auchenberg** [comment] 2019-11-13 00:52
@pitops Do you have an example app you can share? This is most likely caused by your webpack configuration.

**Comment by auchenberg** [comment] 2020-03-20 02:57
Closing due to in activity.

**Closed by auchenberg** 2020-03-20 02:57 UTC
Labels: question
